package tt.badu.ui.vulcat;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import core.db.Database;
import core.reporter.enums.Severity;
import core.reporter.Vulnerability;
import core.reporter.enums.Category;
import core.reporter.enums.Domain;
import java.awt.Color;
import javax.swing.JComboBox;
import tt.badu.ui.master.UpdateCallback;

/**
 *
 * @author mk
 */
public class Catalog extends javax.swing.JFrame {

    private UpdateCallback callback;
    private List<Vulnerability> vulcatList = new ArrayList<>();
    private int lastIndex = 0;
    private boolean isEditing = false;

    /**
     * Creates new form Main
     */
    public Catalog(UpdateCallback callback) {
        this.callback = callback;
        initComponents();
        init();
        start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taBody = new javax.swing.JTextArea();
        tTitleBox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cbSeverity = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbDomain = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cbCategory = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taRecommendation = new javax.swing.JTextArea();
        bEdit = new javax.swing.JButton();
        bSave = new javax.swing.JButton();
        bAdd = new javax.swing.JButton();
        bDelete = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        tfSearchBox = new HintTextField("Ara:");
        jScrollPane1 = new javax.swing.JScrollPane();
        jList = new javax.swing.JList<>(new DefaultListModel<Vulnerability>());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Katalog");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jSplitPane1.setDividerLocation(300);

        jPanel1.setBackground(new java.awt.Color(194, 123, 52));

        taBody.setEditable(false);
        taBody.setColumns(20);
        taBody.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        taBody.setLineWrap(true);
        taBody.setRows(5);
        taBody.setToolTipText("Açıklama...");
        taBody.setWrapStyleWord(true);
        taBody.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                taBodyKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(taBody);

        tTitleBox.setEditable(false);
        tTitleBox.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        jLabel1.setText("Severity");

        cbSeverity.setFocusable(false);
        cbSeverity.setMinimumSize(new java.awt.Dimension(52, 33));

        jLabel3.setText("Domain");

        cbDomain.setFocusable(false);
        cbDomain.setPreferredSize(new java.awt.Dimension(52, 33));

        jLabel4.setText("Category");

        cbCategory.setFocusable(false);
        cbCategory.setMinimumSize(new java.awt.Dimension(52, 33));

        jLabel2.setText("Çözüm Önerisi");

        taRecommendation.setEditable(false);
        taRecommendation.setColumns(20);
        taRecommendation.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        taRecommendation.setLineWrap(true);
        taRecommendation.setWrapStyleWord(true);
        taRecommendation.setRows(5);
        taRecommendation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                taRecommendationKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(taRecommendation);

        bEdit.setText("Edit");
        bEdit.setPreferredSize(new java.awt.Dimension(100, 29));
        bEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditActionPerformed(evt);
            }
        });

        bSave.setText("Save");
        bSave.setEnabled(false);
        bSave.setPreferredSize(new java.awt.Dimension(100, 29));
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });

        bAdd.setText("Add");
        bAdd.setPreferredSize(new java.awt.Dimension(100, 29));
        bAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddActionPerformed(evt);
            }
        });

        bDelete.setText("Delete");
        bDelete.setPreferredSize(new java.awt.Dimension(100, 29));
        bDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tTitleBox, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbSeverity, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbDomain, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbCategory, 0, 282, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(bEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tTitleBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbSeverity, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3)
                        .addComponent(cbDomain, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(cbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel1);

        tfSearchBox.setToolTipText("Ara");
        tfSearchBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfSearchBoxKeyReleased(evt);
            }
        });

        jList.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfSearchBox, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1)
                    .addContainerGap()))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfSearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(558, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jSplitPane1.setLeftComponent(jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListValueChanged
        Vulnerability v = jList.getSelectedValue();
        fillUI(v);
    }//GEN-LAST:event_jListValueChanged

    private int okCancel(String theMessage) {
        int result = JOptionPane.showConfirmDialog(this, theMessage,
                "Uyarı", JOptionPane.OK_CANCEL_OPTION);
        return result;
    }

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        callback.update("Katalog kapatıldı.");
    }//GEN-LAST:event_formWindowClosed

    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed

        lastIndex = jList.getSelectedIndex();
        Vulnerability v = jList.getSelectedValue();

        int result = okCancel(v.getTitle() + " bulgusu silinecektir, onaylıyor musunuz?");

        if (result == JOptionPane.OK_OPTION) {
            delete(v);
            callback.update("Katalaog güncelleme, Zafiyet Silindi: " + v.getTitle());

            int size = jList.getModel().getSize();
            if (size == 0) {
                return;
            } else if (lastIndex == 0) {
                jList.setSelectedIndex(0);
            } else {
                jList.setSelectedIndex(lastIndex - 1);
            }
        }
    }//GEN-LAST:event_bDeleteActionPerformed

    private void bAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddActionPerformed
        String action = bAdd.getText();
        if (action.equals("Add")) {
            add();
        } else {
            cancel();
        }
    }//GEN-LAST:event_bAddActionPerformed

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        bEdit.setEnabled(true);
        bSave.setEnabled(false);
        bAdd.setEnabled(true);
        bDelete.setEnabled(true);
        bAdd.setText("Add");

        String title = tTitleBox.getText().trim();
        String severity = String.valueOf(cbSeverity.getSelectedItem());
        String domain = String.valueOf(cbDomain.getSelectedItem());
        String category = String.valueOf(cbCategory.getSelectedItem());
        String body = taBody.getText().trim();
        String recommendation = taRecommendation.getText().trim();

        if (title.equals("") || body.equals("")) {
            return;
        }

        if (isEditing) {
            Vulnerability v = jList.getSelectedValue();
            delete(v);
        }

        Vulnerability v = new Vulnerability(title, Severity.get(severity), body, recommendation, Domain.get(domain), Category.get(category));
        boolean result = Database.init().insert(v);
        if (result) {
            addToList(v);
            JOptionPane.showMessageDialog(this, "Kaydedildi", "OK", JOptionPane.INFORMATION_MESSAGE);
            callback.update("Katalaog güncelleme, Yeni Zafiyet: " + v.getTitle());
        } else {
            JOptionPane.showMessageDialog(this, "Kayıt Basarisiz", "HATA", JOptionPane.ERROR_MESSAGE);
        }

        jList.setSelectedIndex(jList.getModel().getSize() - 1);

        isEditing = false;
    }//GEN-LAST:event_bSaveActionPerformed

    private void bEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditActionPerformed
        tTitleBox.setEditable(true);
        cbSeverity.setEditable(true);
        taBody.setEditable(true);
        taRecommendation.setEditable(true);

        bEdit.setEnabled(false);
        bSave.setEnabled(true);
        bAdd.setEnabled(false);
        bDelete.setEnabled(false);

        isEditing = true;
    }//GEN-LAST:event_bEditActionPerformed

    private void taRecommendationKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_taRecommendationKeyPressed
        consumeTabKey(evt, taRecommendation);
    }//GEN-LAST:event_taRecommendationKeyPressed

    private void taBodyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_taBodyKeyPressed
        consumeTabKey(evt, taBody);
    }//GEN-LAST:event_taBodyKeyPressed

    private void tfSearchBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSearchBoxKeyReleased
        String queryParam = tfSearchBox.getText();
        if(queryParam.length() < 3) start();
        else search(queryParam);
    }//GEN-LAST:event_tfSearchBoxKeyReleased

    private void consumeTabKey(java.awt.event.KeyEvent evt, JTextArea jta) {
        if (evt.getKeyCode() == KeyEvent.VK_TAB) {
            if (evt.getModifiers() > 0) {
                jta.transferFocusBackward();
            } else {
                jta.transferFocus();
            }
            evt.consume();
        }
    }

    private void delete(Vulnerability v) {
        if (v == null) {
            return;
        }
        boolean result = Database.init().delete(v);
        if (!isEditing) {
            if (result) {
                JOptionPane.showMessageDialog(this, "Silindi", "OK", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Kayıt Silinemedi", "HATA", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        DefaultListModel model = (DefaultListModel) jList.getModel();
        int selectedIndex = jList.getSelectedIndex();
        if (selectedIndex != -1) {
            model.remove(selectedIndex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAdd;
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bEdit;
    private javax.swing.JButton bSave;
    private javax.swing.JComboBox<String> cbCategory;
    private javax.swing.JComboBox<String> cbDomain;
    private javax.swing.JComboBox<String> cbSeverity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<Vulnerability> jList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField tTitleBox;
    private javax.swing.JTextArea taBody;
    private javax.swing.JTextArea taRecommendation;
    private javax.swing.JTextField tfSearchBox;
    // End of variables declaration//GEN-END:variables

    private void start() {
        vulcatList = Database.init().selectAll();
        addToList(vulcatList);

        jList.setSelectedIndex(0);

        if (jList.getModel().getSize() == 0) {
            bEdit.setEnabled(false);
            bSave.setEnabled(false);
            bAdd.setEnabled(true);
        }
    }

    private void addToList(Vulnerability v) {
        ((DefaultListModel) jList.getModel()).addElement(v);
    }

    private void addToList(List<Vulnerability> vulcatList) {
        vulcatList.forEach((v) -> {
            addToList(v);
        });
    }

    private void fillUI(Vulnerability v) {
        if (v == null) {
            return;
        }
        tTitleBox.setText(v.getTitle());
        taBody.setText(v.getBody());
        taRecommendation.setText(v.getRecommendation());

        findAndSelectComboBoxItem(cbSeverity, v.getSeverity().getName());
        findAndSelectComboBoxItem(cbDomain, v.getDomain().getName());
        findAndSelectComboBoxItem(cbCategory, v.getCategory().getName());
    }

    private void findAndSelectComboBoxItem(JComboBox box, String val) {
        int catCount = box.getModel().getSize();
        for (int i = 0; i < catCount; i++) {
            if (val.equals(box.getModel().getElementAt(i))) {
                box.setSelectedIndex(i);
                break;
            }
        }
    }

    private void add() {
        lastIndex = jList.getSelectedIndex();

        bAdd.setText("Cancel");

        bEdit.setEnabled(false);
        bSave.setEnabled(true);
        bAdd.setEnabled(true);
        bDelete.setEnabled(false);

        tTitleBox.setText("");
        tTitleBox.setEditable(true);

        cbSeverity.setSelectedIndex(0);
        cbSeverity.setEditable(true);

        taBody.setText("");
        taBody.setEditable(true);

        taRecommendation.setText("");
        taRecommendation.setEditable(true);
    }

    private void cancel() {
        bAdd.setText("Add");

        bEdit.setEnabled(true);
        bSave.setEnabled(false);
        bAdd.setEnabled(true);
        bDelete.setEnabled(true);

        jList.setSelectedIndex(lastIndex);
    }

    private void init() {
        Severity severityVals[] = Severity.values();
        String severityTitles[] = new String[severityVals.length];
        for (int i = 0; i < severityVals.length; i++) {
            severityTitles[i] = severityVals[i].getName();
        }
        cbSeverity.setModel(new javax.swing.DefaultComboBoxModel<>(severityTitles));

        Domain domainVals[] = Domain.values();
        String domainTitles[] = new String[domainVals.length];
        for (int i = 0; i < domainVals.length; i++) {
            domainTitles[i] = domainVals[i].getName();
        }
        cbDomain.setModel(new javax.swing.DefaultComboBoxModel<>(domainTitles));

        Category categoryVals[] = Category.values();
        String catTitles[] = new String[categoryVals.length];
        for (int i = 0; i < categoryVals.length; i++) {
            catTitles[i] = categoryVals[i].getName();
        }
        cbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(catTitles));

        tfSearchBox.setForeground(Color.GRAY);
        jList.requestFocus();
    }

    private void search(final String queryParam) {
        List<Vulnerability> result = Database.init().search(queryParam);
        for(Vulnerability v : result)
            System.out.println(v.getTitle());
            
        ((DefaultListModel)jList.getModel()).removeAllElements();
        vulcatList.clear();
        addToList(result);

        jList.setSelectedIndex(0);

        if (jList.getModel().getSize() == 0) {
            bEdit.setEnabled(false);
            bSave.setEnabled(false);
            bAdd.setEnabled(true);
        }
    }
}
