package tt.badu.ui.excel;

import core.reporter.excel.enums.DefectTipi;
import core.reporter.excel.enums.Ortam;
import core.reporter.excel.enums.Sirket;
import core.reporter.excel.enums.TestTeam;
import core.reporter.excel.enums.UygulamaOrtami;
import tt.badu.ui.master.RowDataCallback;
import tt.badu.ui.master.UpdateCallback;

/**
 *
 * @author tt
 */
public class BulguOzetForm extends javax.swing.JDialog {

    private final RowDataCallback callback;
    private final UpdateCallback updater;
    private DynamicRowData drd;

    /**
     * Creates new form NewJDialog
     */
    public BulguOzetForm(java.awt.Frame parent, boolean modal, DynamicRowData drd) {
        super(parent, modal);
        callback = (RowDataCallback) parent;
        updater = (UpdateCallback) parent;
        this.drd = drd;
        init(parent);
    }

    private final void init(final java.awt.Frame parent) {
        setTitle("Bulgu Özeti");
        setLocationRelativeTo(parent);
        initComponents();
        fillComboBoxes();

        if (drd != null) {
            populateUI(drd);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfEtkilenenSistem = new javax.swing.JTextField();
        cbTester = new javax.swing.JComboBox<>();
        tfDefectSorumlusu = new javax.swing.JTextField();
        tfProjeYöneticisi = new javax.swing.JTextField();
        tfSorumluDirektorluk = new javax.swing.JTextField();
        cbOrtam = new javax.swing.JComboBox<>();
        cbDefectType = new javax.swing.JComboBox<>();
        jbSave = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cbSirket = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cbTip = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel1.setText("Etkilenen Sistem");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setText("Test Kontağı");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setText("Defect Sorumlusu");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel4.setText("Proje Yöneticisi");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setText("Sorumlu Direktörlük");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel6.setText("Ortam");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel7.setText("Defect Tipi");

        tfEtkilenenSistem.setPreferredSize(new java.awt.Dimension(10, 33));
        tfEtkilenenSistem.setSize(new java.awt.Dimension(80, 50));

        cbTester.setPreferredSize(new java.awt.Dimension(138, 33));
        cbTester.setSize(new java.awt.Dimension(96, 33));

        tfDefectSorumlusu.setPreferredSize(new java.awt.Dimension(10, 33));

        tfProjeYöneticisi.setPreferredSize(new java.awt.Dimension(10, 33));

        tfSorumluDirektorluk.setPreferredSize(new java.awt.Dimension(10, 33));

        cbOrtam.setNextFocusableComponent(cbDefectType);
        cbOrtam.setPreferredSize(new java.awt.Dimension(84, 33));

        cbDefectType.setNextFocusableComponent(cbSirket);
        cbDefectType.setPreferredSize(new java.awt.Dimension(129, 33));

        jbSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tt/badu/image/Box-Down.png"))); // NOI18N
        jbSave.setText("Kaydet");
        jbSave.setToolTipText("");
        jbSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbSave.setNextFocusableComponent(tfEtkilenenSistem);
        jbSave.setPreferredSize(new java.awt.Dimension(100, 62));
        jbSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSaveActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel8.setText("Şirket");

        cbSirket.setNextFocusableComponent(jbSave);
        cbSirket.setPreferredSize(new java.awt.Dimension(84, 33));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel9.setText("Tip");

        cbTip.setNextFocusableComponent(jbSave);
        cbTip.setPreferredSize(new java.awt.Dimension(84, 33));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfEtkilenenSistem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfDefectSorumlusu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfProjeYöneticisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfSorumluDirektorluk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbDefectType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbOrtam, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbSirket, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbTip, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(jbSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbTester, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfEtkilenenSistem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbTester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfDefectSorumlusu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfProjeYöneticisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfSorumluDirektorluk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cbOrtam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(cbSirket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cbDefectType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(cbTip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jbSave, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSaveActionPerformed
        saveAndReturn();
        this.dispose();
    }//GEN-LAST:event_jbSaveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbDefectType;
    private javax.swing.JComboBox<String> cbOrtam;
    private javax.swing.JComboBox<String> cbSirket;
    private javax.swing.JComboBox<String> cbTester;
    private javax.swing.JComboBox<String> cbTip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbSave;
    private javax.swing.JTextField tfDefectSorumlusu;
    private javax.swing.JTextField tfEtkilenenSistem;
    private javax.swing.JTextField tfProjeYöneticisi;
    private javax.swing.JTextField tfSorumluDirektorluk;
    // End of variables declaration//GEN-END:variables

    private void saveAndReturn() {
        String etkilenenSistem = tfEtkilenenSistem.getText();
        String tester = cbTester.getSelectedItem().toString();
        String defectSorumlusu = tfDefectSorumlusu.getText();
        String projeYoneticisi = tfProjeYöneticisi.getText();
        String direktorluk = tfSorumluDirektorluk.getText();
        String ortam = cbOrtam.getSelectedItem().toString();
        String defectTipi = cbDefectType.getSelectedItem().toString();
        String sirket = cbSirket.getSelectedItem().toString();
        String uygulamaOrtami = cbTip.getSelectedItem().toString();

        if (drd == null) {
            drd = new DynamicRowData();
        }
        drd.setEtkilenenSistem(etkilenenSistem);
        drd.setUygulamaOrtami(uygulamaOrtami);
        drd.setTester(tester);
        drd.setDefectSorumlusu(defectSorumlusu);
        drd.setProjeYoneticisi(projeYoneticisi);
        drd.setDirektorluk(direktorluk);
        drd.setOrtam(ortam);
        drd.setDefectTipi(defectTipi);
        drd.setSirket(sirket);

        updater.update("Dinamik hücre verileri kaydedildi.");
        callback.setDynamicRowData(drd);
    }

    private void fillComboBoxes() {
        TestTeam team[] = TestTeam.values();
        String testers[] = new String[team.length];
        for (int i = 0; i < team.length; i++) {
            testers[i] = team[i].getText();
        }
        cbTester.setModel(new javax.swing.DefaultComboBoxModel<>(testers));

        Ortam[] ortamEnums = Ortam.values();
        String ortamVals[] = new String[ortamEnums.length];
        for (int i = 0; i < ortamVals.length; i++) {
            ortamVals[i] = ortamEnums[i].getText();
        }
        cbOrtam.setModel(new javax.swing.DefaultComboBoxModel<>(ortamVals));

        DefectTipi[] defectEnums = DefectTipi.values();
        String defectVals[] = new String[defectEnums.length];
        for (int i = 0; i < defectVals.length; i++) {
            defectVals[i] = defectEnums[i].getText();
        }
        cbDefectType.setModel(new javax.swing.DefaultComboBoxModel<>(defectVals));

        Sirket[] sirketEnums = Sirket.values();
        String sirketVals[] = new String[sirketEnums.length];
        for (int i = 0; i < sirketVals.length; i++) {
            sirketVals[i] = sirketEnums[i].getText();
        }
        cbSirket.setModel(new javax.swing.DefaultComboBoxModel<>(sirketVals));
        
        UygulamaOrtami[] tipEnums = UygulamaOrtami.values();
        String tipVals[] = new String[tipEnums.length];
        for (int i = 0; i < tipVals.length; i++) {
            tipVals[i] = tipEnums[i].getText();
        }
        cbTip.setModel(new javax.swing.DefaultComboBoxModel<>(tipVals));
    }

    private void populateUI(DynamicRowData drd) {
        tfEtkilenenSistem.setText(drd.getEtkilenenSistem());
        TestTeam team[] = TestTeam.values();
        for (int i = 0; i < team.length; i++) {
            if (drd.getTester().equals(team[i].getText())) {
                cbTester.setSelectedIndex(i);
                break;
            }
        }
        tfDefectSorumlusu.setText(drd.getDefectSorumlusu());
        tfProjeYöneticisi.setText(drd.getProjeYoneticisi());
        tfSorumluDirektorluk.setText(drd.getDirektorluk());

        Ortam[] ortamEnums = Ortam.values();
        for (int i = 0; i < ortamEnums.length; i++) {
            if (drd.getOrtam().equals(ortamEnums[i].getText())) {
                cbOrtam.setSelectedIndex(i);
            }
        }

        DefectTipi[] defectEnums = DefectTipi.values();
        for (int i = 0; i < defectEnums.length; i++) {
            if (drd.getDefectTipi().equals(defectEnums[i].getText())) {
                cbDefectType.setSelectedIndex(i);
            }
        }

        Sirket[] sirketEnums = Sirket.values();
        for (int i = 0; i < sirketEnums.length; i++) {
            if (drd.getSirket().equals(sirketEnums[i].getText())) {
                cbSirket.setSelectedIndex(i);
            }
        }
        
        UygulamaOrtami[] tipEnums = UygulamaOrtami.values();
        for (int i = 0; i < tipEnums.length; i++) {
            if (drd.getUygulamaOrtami().equals(tipEnums[i].getText())) {
                cbTip.setSelectedIndex(i);
            }
        }
    }
}
